### ISSUE TITLE
Session Proposal Template

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/2016-Q3-Workshop#3]
For each proposed session, we'll have 1 issue, with the "Session Proposal" label, with the following template.
### Session Proposal Template

Post an issue with this template:
- **Title**: (a short title)
- **Led by**: (who is leading this?)
- **Description**: (the why? the how? and the what?)
- **Goal(s)**: (list the goal(s) of the session, with a list of checkboxes)
- **Target Participants**: (Everyone, people interested in js, etc..)
- **Related Sessions**: (link to other sessions (if any) this one is related to-- to aid scheduling them back to back)
- **Proposed Length**: (choose one of: 15min, 30min, 45min, 60min, 90min)
- **Links to review beforehand**: (anything people should read before coming)
### Example
- **Title**: The HTTP API Spec
- **Led by**: @RichardLitt
- **Description**: I would like to see @RichardLitt talk about the HTTP-API-Spec, available at ipfs/http-api-spec, and how it works. 
- **Goal(s)**:
  - [ ] Overview of Apiary
  - [ ] Overview of how .apib files work
  - [ ] An example log from IPFS and how to update the HTTP API Spec
- **Target Participants**: Everyone
- **Related Sessions**: None.
- **Proposed Length**: 30min
- **Links to review beforehand**:
  - https://github.com/ipfs/http-api-spec
  - docs.ipfs.apiary.io/#

**Comment by daviddias** [comment]
Let's try to get some of the sessions in that we already know we want to have. Could the primary leads open the issues for those, please?
- [x] Packet Switching @lgierth 
- [x] Data Importers
- [x] IPLD Selectors @nicola
- [x] Migration path to IPLD
- [x] Key Revocation and Rotation for IPRS
- [x] Scalable P2P pubsub
- [x] API Tokens for the HTTP-API @Kubuxu 
- [x] Peergos Integration
- [x] Bitswap strategies, make the block exchange even more efficient (https://github.com/ipfs/notes/issues/20)
