### ISSUE TITLE
Session Proposal: Designing IPLD Selectors

### ISSUE THREAD

**Issue by nicola** [ipfs/2016-Q3-Workshop#5]
- **Title**: Designing IPLD Selectors
- **Led by**: @nicola (@jbenet?)
- **Description**:

---
# IPLD Selectors

> IPLD Selectors aim at making document traversal trivial.
## Requirements
- MUST always return a virtual graph (subset or aggregation of the original graph)
- MUST be reliable (no elements are skipped)
- MUST be simple and fast (at the cost of being less expressive, easy to implement)
- MUST work across different objects
- (surely others)
### Arguments on making the language into the path scheme
- pro: usable paths
- pro: can be used as pointers
- pro: IPLD graphs can be mounted
- cons: character limit in URL
- cons: may limit expressiveness (e.g. `hash/book[price>0,author=="Nicola"]`)
- e.g. `hash/*/book`
- e.g. `hash/*/friends[age>30]`
### Possible name spaces

There are multiple name space where it can be:
- **In `/ipld/` or `ipfs`**: built into IPLD
  - pro: convenient
  - pro: can be hidden, one could just use (`HASH/*/name`)
  - pro: by having it into IPLD every IPLD implementor must support it (no way a client can't do query)
  - cons: makes namespace more complex & makes IPLD implementations more complex
  - cons: limit only to one type of `/select/` (e.g. select/selectAll)
- **In `/select/`**: 
  - pro: makes it a nice layer on top of IPLD
  - pro: new namespaces could be created `/select`, `/selectAll` or `/select/all/`, `/select/one/`
  - cons: less convenient
  - cons: can't be hidden (unless application uses some heuristics, e.g. detect `[`, detect `*`)
- **In `/transform/select/`**:
  - pro: treated as a special native transformation
  - pro: layers well on top of transformation that layers on top of IPLD
    - anyone could implement their own selector `/transform/HashOfSelectorTransform/HashOfObj`
  - cons: longer path name
## Selector language

In this section we will use this example

```
hashLibrary                    hashBook1       hashBook2       hashBook3
{                              {               {               {
  books: {                       title: 'B1',    title: 'B2',    title: 'B3',
    "book1": hashBook1,          type: 'a',      type: 'a',      type: 'b',
    "book2": hashBook2,          price: 10       price: 30,      price: 50
    "book3": hashBook3,        }               }               }
  },
  location: "Rome"
}
```
### Selecting known nodes (trivial)
- `hash`, or `hash+IPLD pointer`
### Selecting unknown nodes

This is the equivalent of pointing to multiple nodes in the path

Examples:
- `hash/*/name`
- `hash/*/*`
- `hash/**/test`
- `hash/**/test`
- `hash/test*/name`
- `hash/te*st/name`
### Filters with expressions

This is not the equivalent of pointing to multiple nodes and can be implemented in different ways:
- Filtering parents/Filtering the graph (just filter the nodes that contain the attributes without transforming the matching graphs)
- Filtering childrens/Aggregating results (filters the nodes and only returns the attributes as if they were nodes)

Examples:
- `hash/books/*[price>30]`
- `hash/books[price>30]`
- `hash/books/[price>30]`
- `hash/books/[*>30]`
- `hash/books[price>0,author=="Nicola"]`
- `hash/books[price>0 && author=="Nicola"]`
### Filters with predicates
- `hash/books/last()`
- `hash/books/[last()]`
- `hash/books/[position()<3]`
- `hash/books/[endsWith(3) == 'ok1']`
### Filters with regex
- `/hash/book/.*/book.`
## Verifiability

Return values of a selector query cannot be trusted unless run on the user own machine (even then, the user must trust that he has the right blocks). While returning the result, the selector computation should return a proof - which could be streamed to the user - and then checked.

This proof should be a proof of (non)membership.
## Read before
- [Why JSON Pointer falls short](http://susanpotter.net/blogs/software/2011/07/why-json-pointer-falls-short/)
- [XPath](http://www.w3schools.com/xsl/xpath_syntax.asp)
- [IPLD selector notes](https://github.com/ipfs/notes/issues/12)
## Existing Candidates
- Subset of XPath
- Globbing
## TODO:
- [ ] agree on pathing name space
- [ ] agree on `select1`, `selectAll`
- [ ] define a set of filters
- [ ] agree on multiple-filters or single-filter usage

---
- **Target Participants**: @jbenet @dignifiedquire @mildred @stebalien
- **Dependencies**:
- **Related Sessions**: IPLD
- **Proposed Length**: 30/45 mins
- **Links to review beforehand**:
  - Roadmap towards IPLD: https://github.com/ipfs/specs/issues/115
  - New abstractions in IPLD: https://github.com/ipfs/specs/issues/91

**Comment by chriscool** [comment]
@nicola @jbenet thanks for the session!

**Comment by nicola** [comment]
Notes taken here: https://github.com/ipld/specs/issues/4
